version: "3"

services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017/meteor
      - ROOT_URL=http://0.0.0.0/
    links:
      - "mongo:mongo"
    depends_on:
      - mongo
    expose:
      - 3000
    networks:
      - default

  mongo:
    image: mongo:3.0
    volumes:
      - /data/db
    ports:
      - "3001:27017"
    networks:
      - default
